import Footer from "@/components/Shared/Footer"
import Navbar from "@/components/Shared/Navbar"
import '../app/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <Navbar />
          <main>{children}</main>
          <Footer />
      </body>
    </html>
  )
}
